name: PiG
version: 0.1.2
github: PKopel/PiG
license: BSD3
author: Paweł Kopel
maintainer: pawel.kopel2@gmail.com
copyright: 2022 Paweł Kopel

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/PKopel/PiG#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - rio-orphans
  - containers
  - mtl
  - text
  - array
  - attoparsec
  - exceptions
  - haskeline >= 0.8
  - pretty-terminal

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  build-tools:
    - alex
    - happy

executables:
  pig:
    main: Main.hs
    source-dirs: app
    dependencies:
      - PiG
      - optparse-simple
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  pig-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - PiG
      - hspec
      - hspec-core
      - QuickCheck

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
