name: Unit tests

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stack:
    name: stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["3.3.1"]
        ghc: ["9.6.4"]

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Setup stack cache
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --dry-run
          install-stack: false
          upgrade-stack: false

      - name: Build
        run: |
          stack --system-ghc build --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack --system-ghc test
