name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stack:
    name: stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["3.3.1"]
        ghc: ["9.6.4"]

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        with:
          enable-stack: true
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: freckle/stack-cache-action@v2

      - name: Build
        run: |
          stack --system-ghc build --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack --system-ghc test
